---
name: Fix
run-name: Fix (${{ github.event.label.name }})
on:
  label:
    types:
      - created
jobs:
  fix:
    if: startsWith(github.event.label.name, 'securefix-')
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    environment: main
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          sparse-checkout: |
            securefix-action.yaml
          sparse-checkout-cone-mode: false
      - uses: csm-actions/securefix-action/server/prepare@78d48e92c3c5812f4bac9a4f906b0f1b52dad655 # pr/208
        id: prepare
        with:
          app_id: ${{ vars.TEST_SERVER_APP_ID }}
          app_private_key: ${{ secrets.DEMO_SERVER_PRIVATE_KEY }}
          config_file: securefix-action.yaml
      - uses: csm-actions/securefix-action/server/commit@78d48e92c3c5812f4bac9a4f906b0f1b52dad655 # pr/208
        with:
          outputs: ${{ toJson(steps.prepare.outputs) }}
      - uses: csm-actions/securefix-action/server/notify@78d48e92c3c5812f4bac9a4f906b0f1b52dad655 # pr/208
        if: failure()
        with:
          outputs: ${{ toJson(steps.prepare.outputs) }}
