---
name: Update Branch
run-name: Update Branch (${{ github.event.label.name }})
on:
  label:
    types:
      - created
jobs:
  update_branch:
    if: startsWith(github.event.label.name, 'update-branch-')
    name: Update Branch (${{ github.event.label.description }})
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    environment: main
    permissions: {}
    steps:
      - uses: csm-actions/update-branch-action/server@105a6c8d00edd27a4a1f81188e3b24f27e6fd0ab # v0.1.1
        with:
          app_id: ${{ vars.DEMO_SERVER_APP_ID }}
          app_private_key: ${{ secrets.DEMO_SERVER_PRIVATE_KEY }}
